name: deploying the nextjs application to the vm

on:
    push:
        branches: [ main ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: login to a vm && start the fe-server
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ vars.VM_IP4_ADDRESS }}
                username: ubuntu
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                    whoami