name: deploying the nextjs application to the vm

on:
    push:
        branches: [ main ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: login to a vm && start the fe-server
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ vars.VM_IP4_ADDRESS }}
                username: ubuntu
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                    whoami
                    cd week-25-ci-cd-sargam
                    git pull origin main
                    export PATH=$HOME/.nvm/versions/node/v23.11.0/bin:$PATH
                    npm install
                    pm2 restart fe-server || pm2 start npm --name "fe-server" -- start