name: deploying the nextjs application to the vm

on:
    push:
        branches: [ main ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: login to a vm
              run: | 
                mkdir ~/.ssh
                touch ~/.ssh known_hosts
                echo "${{ secrets.KNOWN_HOSTS }}" &> ~/.ssh/known_hosts
                echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
                chmod 700 ~/ssh_key
                ssh -i ~/ssh_key ubuntu@${{ vars.VM_IP4_ADDRESS }}

            - name: pull changes & run the start script
              run: |
                -t "cd ~/week-25-ci-cd-sargam && git pull origin main && npm install"